services:
  app:
    container_name: api_mobi
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: pnpm start:dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis_mobi
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  db:
    image: postgres:latest
    container_name: db_mobi
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  redis:
      driver: local
  pgdata:
    driver: local
